from datetime import datetime, timezone


def render_feed_markdown(postings: list[dict], newly_added_ids: set, source_label: str, filter_name: str = "") -> str:
    """postings: list of posting dicts (id/company/title/location/url/category/first_seen/...).
    Shared by scrape.py (writes the raw, unfiltered feed isn't rendered — see
    build_feed.py) and build_feed.py (writes a personalized filtered feed).
    """
    title_suffix = f" — {filter_name}" if filter_name else ""
    lines = [
        f"# Live Opportunity Feed{title_suffix}",
        "",
        f"Auto-generated by `{source_label}` — last updated "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "Do not hand-edit; changes are overwritten on the next run.",
        "",
        f"{len(postings)} open posting(s) currently tracked.",
        "",
    ]
    by_category: dict[str, list] = {}
    for p in postings:
        by_category.setdefault(p.get("category") or "Uncategorized", []).append(p)

    for category in sorted(by_category):
        lines.append(f"## {category}")
        lines.append("")
        for p in by_category[category]:
            flag = " 🆕" if p["id"] in newly_added_ids else ""
            loc = f" — {p['location']}" if p.get("location") else ""
            lines.append(f"- [{p['company']}: {p['title']}]({p['url']}){loc}{flag} (first seen {p['first_seen'][:10]})")
        lines.append("")

    return "\n".join(lines)
