#!/usr/bin/env python3
"""Fetch current internship postings from every source in sources.yaml,
filter to ops/logistics/supply-chain, and update data/opportunities.json
+ FEED.md. Run manually (`python scraper/scrape.py`) or on a schedule via
.github/workflows/scrape.yml.

Exits non-zero on a source that errors, AFTER processing every other
source — one broken/renamed token shouldn't hide postings from the rest.
"""
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from connectors import CONNECTORS  # noqa: E402
from filters import is_relevant  # noqa: E402
from store import load_opportunities, rebuild, save_opportunities  # noqa: E402

ROOT = Path(__file__).parent.parent
SOURCES_FILE = ROOT / "sources.yaml"
DATA_FILE = ROOT / "data" / "opportunities.json"
FEED_FILE = ROOT / "FEED.md"


def load_sources() -> list[dict]:
    with SOURCES_FILE.open() as f:
        config = yaml.safe_load(f) or {}
    return config.get("sources", [])


def fetch_all(sources: list[dict]) -> tuple[list, list[str]]:
    all_postings = []
    errors = []
    for entry in sources:
        ats = entry.get("ats")
        connector_cls = CONNECTORS.get(ats)
        if connector_cls is None:
            errors.append(f"{entry.get('company', '?')}: unknown ats '{ats}' (known: {list(CONNECTORS)})")
            continue
        try:
            postings = connector_cls().fetch(entry)
        except Exception as exc:  # noqa: BLE001 - one bad source must not kill the run
            errors.append(f"{entry.get('company', '?')} ({ats}): {exc}")
            continue
        domain_native = bool(entry.get("domain_native"))
        relevant = [p for p in postings if is_relevant(p.title, p.description_snippet, domain_native)]
        all_postings.extend(relevant)
        print(f"  {entry.get('company', '?'):30s} {len(postings):4d} fetched -> {len(relevant):3d} relevant")
    return all_postings, errors


def write_feed(store: dict, newly_added_ids: set) -> None:
    postings = sorted(store.values(), key=lambda p: p.get("first_seen", ""), reverse=True)
    lines = [
        "# Live Opportunity Feed",
        "",
        f"Auto-generated by `scraper/scrape.py` — last updated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "Do not hand-edit; changes are overwritten on the next run.",
        "",
        f"{len(postings)} open posting(s) currently tracked, from `sources.yaml`.",
        "",
    ]
    by_category: dict[str, list] = {}
    for p in postings:
        by_category.setdefault(p.get("category") or "Uncategorized", []).append(p)

    for category in sorted(by_category):
        lines.append(f"## {category}")
        lines.append("")
        for p in by_category[category]:
            flag = " 🆕" if p["id"] in newly_added_ids else ""
            loc = f" — {p['location']}" if p.get("location") else ""
            lines.append(f"- [{p['company']}: {p['title']}]({p['url']}){loc}{flag} (first seen {p['first_seen'][:10]})")
        lines.append("")

    FEED_FILE.write_text("\n".join(lines))


def main() -> int:
    sources = load_sources()
    print(f"Fetching {len(sources)} source(s)...")
    fresh_postings, errors = fetch_all(sources)

    previous = load_opportunities(DATA_FILE)
    seen_at = datetime.now(timezone.utc).isoformat()
    new_store, newly_added = rebuild(previous, fresh_postings, seen_at)
    save_opportunities(DATA_FILE, new_store)
    write_feed(new_store, {p["id"] for p in newly_added})

    print(f"\n{len(new_store)} open posting(s) tracked, {len(newly_added)} new this run.")
    for p in newly_added:
        print(f"  NEW: {p['company']} — {p['title']} ({p['url']})")

    if errors:
        print(f"\n{len(errors)} source(s) failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
